--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consignments (
    price numeric(38,2),
    quantity integer,
    create_date timestamp(6) without time zone,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    purchase_order_guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    sku character varying(255) NOT NULL
);


ALTER TABLE public.consignments OWNER TO postgres;

--
-- Name: consignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    address character varying(255),
    bank_card character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventories (
    quantity integer,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.inventories OWNER TO postgres;

--
-- Name: inventories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    inventory_guid uuid NOT NULL,
    description character varying(255),
    location_name character varying(255) NOT NULL
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_details (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    order_guid uuid NOT NULL,
    product_guid uuid NOT NULL
);


ALTER TABLE public.order_details OWNER TO postgres;

--
-- Name: order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    total_price integer,
    id bigint NOT NULL,
    customer_guid uuid NOT NULL,
    guid uuid NOT NULL,
    transaction_guid uuid,
    description character varying(255),
    is_active character varying(255)
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    quantity integer,
    id bigint NOT NULL,
    category_guid uuid NOT NULL,
    consignment_guid uuid,
    guid uuid NOT NULL,
    variant_guid uuid NOT NULL,
    description character varying(255),
    image character varying(255),
    name character varying(255),
    status character varying(255)
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_order_details (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    product_guid uuid NOT NULL,
    purchase_order_guid uuid NOT NULL
);


ALTER TABLE public.purchase_order_details OWNER TO postgres;

--
-- Name: purchase_order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_orders (
    total_price integer NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    description character varying(255) NOT NULL,
    is_active character varying(255) NOT NULL
);


ALTER TABLE public.purchase_orders OWNER TO postgres;

--
-- Name: purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    description character varying(255),
    role_name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggest_purchase_order_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suggest_purchase_order_products (
    price integer NOT NULL,
    quantity integer NOT NULL,
    id bigint NOT NULL,
    suggest_purchase_order_id bigint,
    product_guid uuid NOT NULL
);


ALTER TABLE public.suggest_purchase_order_products OWNER TO postgres;

--
-- Name: suggest_purchase_order_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suggest_purchase_order_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggest_purchase_order_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggest_purchase_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suggest_purchase_orders (
    price integer NOT NULL,
    quantity integer NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    description character varying(255),
    is_active character varying(255)
);


ALTER TABLE public.suggest_purchase_orders OWNER TO postgres;

--
-- Name: suggest_purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suggest_purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggest_purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier_performance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier_performance (
    on_time_delivery_rate numeric(3,2) NOT NULL,
    product_quality_rating numeric(3,2) NOT NULL,
    supply_completion_rate numeric(3,2) NOT NULL,
    id bigint NOT NULL,
    consignment_guid uuid NOT NULL,
    guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    description character varying(255)
);


ALTER TABLE public.supplier_performance OWNER TO postgres;

--
-- Name: supplier_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.supplier_performance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_performance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    address character varying(255),
    email character varying(255),
    is_active character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);


ALTER TABLE public.suppliers OWNER TO postgres;

--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_configs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_configs (
    id bigint NOT NULL,
    config_value character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.system_configs OWNER TO postgres;

--
-- Name: system_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    money numeric(38,2) NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    customer_guid uuid NOT NULL,
    guid uuid NOT NULL,
    description character varying(255)
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transfer_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transfer_requests (
    quantity integer NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    from_inventory_guid uuid NOT NULL,
    guid uuid NOT NULL,
    product_guid uuid NOT NULL,
    to_inventory_guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    note character varying(255)
);


ALTER TABLE public.transfer_requests OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    is_active boolean,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    role_guid uuid NOT NULL,
    contact_info character varying(255),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: variants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.variants (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    color character varying(255),
    size character varying(255)
);


ALTER TABLE public.variants OWNER TO postgres;

--
-- Name: variants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, guid, description, name) FROM stdin;
1	6ace6271-4b0a-40d4-90ad-98129b233b3a	Quần	Quần
2	4c4d0b96-bed1-4634-a396-4041f23fb24f	Áo	Áo
3	79479b47-441d-454d-950e-6b56006de515	Áo Thun	Áo Thun
4	9d0ff93d-ac6f-4776-9c81-d968e694d8d7	Áo Sơ Mi	Áo Sơ Mi
\.


--
-- Data for Name: consignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.consignments (price, quantity, create_date, id, guid, purchase_order_guid, supplier_guid, description, name, sku) FROM stdin;
10.00	10	2025-06-03 22:56:26.913521	3	15a8b639-9f65-4273-a435-ceaba0203151	de8238e4-8af4-458d-8ee5-75824f0338fe	b16e390e-23e2-447c-a94c-c472c253c847	hang hoa	hang hoa	test
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, guid, address, bank_card, email, name, phone) FROM stdin;
1	18d32839-6e07-46f6-ad1d-fad41c7f5e2e	asdfadf	4234324234	vantai@gmail.com	Van tai 	12312321
2	13172b93-5fe3-48f2-8c36-c4029aeef39f	asdfadf	4234324234	taivan@gmail.com	Van tai van	12312321
\.


--
-- Data for Name: inventories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventories (quantity, id, guid, user_guid, description, name) FROM stdin;
\.


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.locations (id, guid, inventory_guid, description, location_name) FROM stdin;
\.


--
-- Data for Name: order_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_details (quantity, id, guid, order_guid, product_guid) FROM stdin;
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (total_price, id, customer_guid, guid, transaction_guid, description, is_active) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (quantity, id, category_guid, consignment_guid, guid, variant_guid, description, image, name, status) FROM stdin;
0	1	6ace6271-4b0a-40d4-90ad-98129b233b3a	\N	a6386522-d30e-4167-a4b3-ccec258cc5f7	d59a941d-69be-48e4-8097-3108303c85e9	quần dài	string	Quần dài	active
0	2	79479b47-441d-454d-950e-6b56006de515	\N	7f28e602-6afa-4428-913f-488560f75fb3	05ee6231-45f8-4202-8d86-f2d3b23183c0	Áo	string	Áo	active
\.


--
-- Data for Name: purchase_order_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchase_order_details (quantity, id, guid, product_guid, purchase_order_guid) FROM stdin;
10	1	6e8b1652-89c3-489d-8aa5-896e6961a0c1	a6386522-d30e-4167-a4b3-ccec258cc5f7	de8238e4-8af4-458d-8ee5-75824f0338fe
10	2	d23e989a-aaa3-4309-8bc8-843d63bdc10c	7f28e602-6afa-4428-913f-488560f75fb3	3f38d75c-249f-4555-a37c-b7b1b8fb6893
12	3	c1226c03-1cf8-423a-926d-4eb25ce8b443	7f28e602-6afa-4428-913f-488560f75fb3	3f38d75c-249f-4555-a37c-b7b1b8fb6893
5	4	1e7dd61a-ab88-46b2-99f2-4149e46eb801	7f28e602-6afa-4428-913f-488560f75fb3	3f38d75c-249f-4555-a37c-b7b1b8fb6893
\.


--
-- Data for Name: purchase_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchase_orders (total_price, id, guid, supplier_guid, description, is_active) FROM stdin;
100000	1	de8238e4-8af4-458d-8ee5-75824f0338fe	f477101a-3b8b-40ac-8ea7-5e154552e370	đồ của adidas	active
100000	2	3f38d75c-249f-4555-a37c-b7b1b8fb6893	f477101a-3b8b-40ac-8ea7-5e154552e370	đồ của adidas	active
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, guid, description, role_name) FROM stdin;
1	371192fd-85e8-417c-9655-2e24439497b9	ADMIN	ADMIN
2	3fa4881c-211a-4e1b-9669-c0713f26167f	MANAGER	MANAGER
3	df0071d3-ebe4-449a-9c37-deb5d4bd6d1a	USER	USER
4	47af06cc-60c6-4bfd-b4b8-e9e6126b1e84	customer	customer
\.


--
-- Data for Name: suggest_purchase_order_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suggest_purchase_order_products (price, quantity, id, suggest_purchase_order_id, product_guid) FROM stdin;
\.


--
-- Data for Name: suggest_purchase_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suggest_purchase_orders (price, quantity, create_date, id, guid, supplier_guid, user_guid, description, is_active) FROM stdin;
\.


--
-- Data for Name: supplier_performance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.supplier_performance (on_time_delivery_rate, product_quality_rating, supply_completion_rate, id, consignment_guid, guid, supplier_guid, user_guid, description) FROM stdin;
\.


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suppliers (id, guid, address, email, is_active, name, phone) FROM stdin;
1	b16e390e-23e2-447c-a94c-c472c253c847	đường nike	nike@gmail.com	active	nhân viên nike	123123123
2	f477101a-3b8b-40ac-8ea7-5e154552e370	đường adidas	adidas@gmail.com	active	nhân viên adidas	123123123
\.


--
-- Data for Name: system_configs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.system_configs (id, config_value, description, name) FROM stdin;
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (money, create_date, id, customer_guid, guid, description) FROM stdin;
\.


--
-- Data for Name: transfer_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transfer_requests (quantity, create_date, from_inventory_guid, guid, product_guid, to_inventory_guid, user_guid, note) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (is_active, id, guid, role_guid, contact_info, email, password, username) FROM stdin;
t	1	3b31c9a7-fe42-45bc-82e2-6f2d5161abff	371192fd-85e8-417c-9655-2e24439497b9	123123123	admind@gmail.com	$2a$10$f/tpAGsoMbgj6W/6G25tl.gkpnI5jur4fgkpaUeUdittpQamxvqRS	ADMIN
t	3	506af662-b4b8-4e63-bf5a-37a9f02946dd	3fa4881c-211a-4e1b-9669-c0713f26167f	123123123	anhtuan@gmail.com	$2a$10$G3zCHyVD9F8QDyuoR.kSteyvxvFlAHAr8A7q1Vxeny6d2TTq2Oiam	anhtuan
t	4	5c10b89d-1588-4fa4-8900-0fe803fd8036	df0071d3-ebe4-449a-9c37-deb5d4bd6d1a	123123123	ductoan@gmail.com	$2a$10$xmTNLIaN8W3duVjszd3MGeaM.PvkBAx/yk7CfMIipTcoxhzwqbbkS	ductoan1
\.


--
-- Data for Name: variants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.variants (id, guid, color, size) FROM stdin;
1	bb6c27c1-2ae5-40c0-9f53-cd3d1fcf05d4	White	S
2	d59a941d-69be-48e4-8097-3108303c85e9	Red	S
3	05ee6231-45f8-4202-8d86-f2d3b23183c0	Red	M
4	8a311b72-5208-401f-b0a6-9ed6f8701f72	White	M
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 4, true);


--
-- Name: consignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.consignments_id_seq', 4, true);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 2, true);


--
-- Name: inventories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventories_id_seq', 1, false);


--
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.locations_id_seq', 1, false);


--
-- Name: order_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_details_id_seq', 1, false);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 2, true);


--
-- Name: purchase_order_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchase_order_details_id_seq', 4, true);


--
-- Name: purchase_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchase_orders_id_seq', 2, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- Name: suggest_purchase_order_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suggest_purchase_order_products_id_seq', 1, false);


--
-- Name: suggest_purchase_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suggest_purchase_orders_id_seq', 1, false);


--
-- Name: supplier_performance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supplier_performance_id_seq', 1, false);


--
-- Name: suppliers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suppliers_id_seq', 2, true);


--
-- Name: system_configs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.system_configs_id_seq', 1, false);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: variants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.variants_id_seq', 4, true);


--
-- Name: consignments UKf7wvmjljuojl6a47s4590tlvd; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consignments
    ADD CONSTRAINT "UKf7wvmjljuojl6a47s4590tlvd" UNIQUE (sku);


--
-- Name: categories categories_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_guid_key UNIQUE (guid);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: consignments consignments_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consignments
    ADD CONSTRAINT consignments_guid_key UNIQUE (guid);


--
-- Name: consignments consignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consignments
    ADD CONSTRAINT consignments_pkey PRIMARY KEY (id);


--
-- Name: consignments consignments_sku_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consignments
    ADD CONSTRAINT consignments_sku_key UNIQUE (sku);


--
-- Name: customers customers_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_guid_key UNIQUE (guid);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: inventories inventories_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_guid_key UNIQUE (guid);


--
-- Name: inventories inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_pkey PRIMARY KEY (id);


--
-- Name: locations locations_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_guid_key UNIQUE (guid);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: order_details order_details_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_guid_key UNIQUE (guid);


--
-- Name: order_details order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);


--
-- Name: orders orders_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_guid_key UNIQUE (guid);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_guid_key UNIQUE (guid);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: purchase_order_details purchase_order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_details
    ADD CONSTRAINT purchase_order_details_pkey PRIMARY KEY (id);


--
-- Name: purchase_orders purchase_orders_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_guid_key UNIQUE (guid);


--
-- Name: purchase_orders purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);


--
-- Name: roles roles_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_guid_key UNIQUE (guid);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- Name: suggest_purchase_order_products suggest_purchase_order_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_order_products
    ADD CONSTRAINT suggest_purchase_order_products_pkey PRIMARY KEY (id);


--
-- Name: suggest_purchase_orders suggest_purchase_orders_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_orders
    ADD CONSTRAINT suggest_purchase_orders_guid_key UNIQUE (guid);


--
-- Name: suggest_purchase_orders suggest_purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_orders
    ADD CONSTRAINT suggest_purchase_orders_pkey PRIMARY KEY (id);


--
-- Name: supplier_performance supplier_performance_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier_performance
    ADD CONSTRAINT supplier_performance_guid_key UNIQUE (guid);


--
-- Name: supplier_performance supplier_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier_performance
    ADD CONSTRAINT supplier_performance_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_guid_key UNIQUE (guid);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: system_configs system_configs_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_configs
    ADD CONSTRAINT system_configs_name_key UNIQUE (name);


--
-- Name: system_configs system_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_configs
    ADD CONSTRAINT system_configs_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_guid_key UNIQUE (guid);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: transfer_requests transfer_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfer_requests
    ADD CONSTRAINT transfer_requests_pkey PRIMARY KEY (guid);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_guid_key UNIQUE (guid);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: variants variants_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.variants
    ADD CONSTRAINT variants_guid_key UNIQUE (guid);


--
-- Name: variants variants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.variants
    ADD CONSTRAINT variants_pkey PRIMARY KEY (id);


--
-- Name: purchase_orders FK27odvxtv2d2w20lsg9qh3ycte; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT "FK27odvxtv2d2w20lsg9qh3ycte" FOREIGN KEY (supplier_guid) REFERENCES public.suppliers(guid);


--
-- Name: products FK3mn9fcv8gawky7rgwnes0e5uf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FK3mn9fcv8gawky7rgwnes0e5uf" FOREIGN KEY (category_guid) REFERENCES public.categories(guid);


--
-- Name: suggest_purchase_order_products FK6a2i0qfvmk80ajh2suo7v49hl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_order_products
    ADD CONSTRAINT "FK6a2i0qfvmk80ajh2suo7v49hl" FOREIGN KEY (suggest_purchase_order_id) REFERENCES public.suggest_purchase_orders(id);


--
-- Name: products FKauhtqrx1mr4b5w6aw3vx7cwk0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FKauhtqrx1mr4b5w6aw3vx7cwk0" FOREIGN KEY (variant_guid) REFERENCES public.variants(guid);


--
-- Name: orders FKdy1mqg6b9c230kh8ndnbh4775; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "FKdy1mqg6b9c230kh8ndnbh4775" FOREIGN KEY (customer_guid) REFERENCES public.customers(guid);


--
-- Name: transactions FKhva4f7ywanet2v96e4uft4xyp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FKhva4f7ywanet2v96e4uft4xyp" FOREIGN KEY (customer_guid) REFERENCES public.customers(guid);


--
-- Name: purchase_order_details FKjer4t22d66ip6hj11xkery5wd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_details
    ADD CONSTRAINT "FKjer4t22d66ip6hj11xkery5wd" FOREIGN KEY (purchase_order_guid) REFERENCES public.purchase_orders(guid);


--
-- Name: order_details FKk3r4d3kuu7vo4nassvxjteqpb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "FKk3r4d3kuu7vo4nassvxjteqpb" FOREIGN KEY (product_guid) REFERENCES public.products(guid);


--
-- Name: products FKllnmoc2pnv65erd9i01vc0y9q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FKllnmoc2pnv65erd9i01vc0y9q" FOREIGN KEY (consignment_guid) REFERENCES public.consignments(guid);


--
-- Name: order_details FKoqqgvqga60e9clqfa3yjbwd8k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "FKoqqgvqga60e9clqfa3yjbwd8k" FOREIGN KEY (order_guid) REFERENCES public.orders(guid);


--
-- Name: users FKssgfe6o9uysoim8bstkkxph37; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "FKssgfe6o9uysoim8bstkkxph37" FOREIGN KEY (role_guid) REFERENCES public.roles(guid);


--
-- PostgreSQL database dump complete
--

