--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consignments (
    price numeric(38,2),
    quantity integer,
    create_date timestamp(6) without time zone,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    purchase_order_guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    sku character varying(255) NOT NULL
);


ALTER TABLE public.consignments OWNER TO postgres;

--
-- Name: consignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    address character varying(255),
    bank_card character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventories (
    quantity integer,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.inventories OWNER TO postgres;

--
-- Name: inventories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    inventory_guid uuid NOT NULL,
    description character varying(255),
    location_name character varying(255) NOT NULL
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_details (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    order_guid uuid NOT NULL,
    product_guid uuid NOT NULL
);


ALTER TABLE public.order_details OWNER TO postgres;

--
-- Name: order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    total_price integer,
    id bigint NOT NULL,
    customer_guid uuid NOT NULL,
    guid uuid NOT NULL,
    transaction_guid uuid,
    description character varying(255),
    is_active character varying(255)
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    quantity integer,
    id bigint NOT NULL,
    category_guid uuid NOT NULL,
    guid uuid NOT NULL,
    variant_guid uuid NOT NULL,
    description character varying(255),
    name character varying(255),
    status character varying(255)
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_order_details (
    quantity integer NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    product_guid uuid NOT NULL,
    purchase_order_guid uuid NOT NULL
);


ALTER TABLE public.purchase_order_details OWNER TO postgres;

--
-- Name: purchase_order_details_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_order_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_orders (
    total_price integer NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    description character varying(255) NOT NULL,
    is_active character varying(255) NOT NULL
);


ALTER TABLE public.purchase_orders OWNER TO postgres;

--
-- Name: purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    description character varying(255),
    role_name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggest_purchase_order_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suggest_purchase_order_products (
    price integer NOT NULL,
    quantity integer NOT NULL,
    id bigint NOT NULL,
    suggest_purchase_order_id bigint,
    product_guid uuid NOT NULL
);


ALTER TABLE public.suggest_purchase_order_products OWNER TO postgres;

--
-- Name: suggest_purchase_order_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suggest_purchase_order_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggest_purchase_order_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suggest_purchase_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suggest_purchase_orders (
    price integer NOT NULL,
    quantity integer NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    description character varying(255),
    is_active character varying(255)
);


ALTER TABLE public.suggest_purchase_orders OWNER TO postgres;

--
-- Name: suggest_purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suggest_purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suggest_purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier_performance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier_performance (
    on_time_delivery_rate numeric(3,2) NOT NULL,
    product_quality_rating numeric(3,2) NOT NULL,
    supply_completion_rate numeric(3,2) NOT NULL,
    id bigint NOT NULL,
    consignment_guid uuid NOT NULL,
    guid uuid NOT NULL,
    supplier_guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    description character varying(255)
);


ALTER TABLE public.supplier_performance OWNER TO postgres;

--
-- Name: supplier_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.supplier_performance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_performance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    address character varying(255),
    email character varying(255),
    is_active character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255)
);


ALTER TABLE public.suppliers OWNER TO postgres;

--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_configs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_configs (
    id bigint NOT NULL,
    config_value character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.system_configs OWNER TO postgres;

--
-- Name: system_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    money numeric(38,2) NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    customer_guid uuid NOT NULL,
    guid uuid NOT NULL,
    description character varying(255)
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transfer_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transfer_requests (
    quantity integer NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    from_inventory_guid uuid NOT NULL,
    guid uuid NOT NULL,
    product_guid uuid NOT NULL,
    to_inventory_guid uuid NOT NULL,
    user_guid uuid NOT NULL,
    note character varying(255)
);


ALTER TABLE public.transfer_requests OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    is_active boolean,
    id bigint NOT NULL,
    guid uuid NOT NULL,
    role_guid uuid NOT NULL,
    contact_info character varying(255),
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: variants; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.variants (
    id bigint NOT NULL,
    guid uuid NOT NULL,
    color character varying(255),
    size character varying(255)
);


ALTER TABLE public.variants OWNER TO postgres;

--
-- Name: variants_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, guid, description, name) FROM stdin;
1	7b830727-ffa3-4689-849c-5ba5a4398ef6	quần short	quần short
2	f1e3467f-644e-4204-93cb-94338ed1fef6	áo sơ mi	áo sơ mi
3	c5a13a44-d8ba-4ca9-9ce9-a81b4f4ab747	áo thun	áo thun
4	b0f1f801-9365-4722-b2d6-da249fa88241	quần dài	quần dài
\.


--
-- Data for Name: consignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.consignments (price, quantity, create_date, id, guid, purchase_order_guid, supplier_guid, description, name, sku) FROM stdin;
100000.00	1	2025-05-12 23:24:28.009368	1	a6dd7a68-60f0-4bee-86ca-dde67fb04477	3d8742e9-79d6-4dc1-90c1-57f32afcca08	f106f51a-b04b-43d0-ac85-d29fc17b5d1d	lo ao tu nike	lo hang tu nike	nike-ao-12/05/2025
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, guid, address, bank_card, email, name, phone) FROM stdin;
1	69bc52f5-d99e-4176-a2d6-daa12132bd60	231/c2	chưa có	vnatai@gmail.com	van tai	9876543210
2	0340cc86-ae26-4a06-8d6f-03b5a12cd5a0	290/c2	chưa có	ngoclong@gmail.com	ngoc long	9876543210
\.


--
-- Data for Name: inventories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventories (quantity, id, guid, user_guid, description, name) FROM stdin;
\.


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.locations (id, guid, inventory_guid, description, location_name) FROM stdin;
\.


--
-- Data for Name: order_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_details (quantity, id, guid, order_guid, product_guid) FROM stdin;
2	1	42413b37-0c1c-4c0a-838c-9767806f8989	207d0d56-d636-4be3-a2b3-54914ca9ab44	8429eecd-fd74-4d0d-903a-35b6b36d800b
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (total_price, id, customer_guid, guid, transaction_guid, description, is_active) FROM stdin;
0	2	69bc52f5-d99e-4176-a2d6-daa12132bd60	207d0d56-d636-4be3-a2b3-54914ca9ab44	\N	string	string
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (quantity, id, category_guid, guid, variant_guid, description, name, status) FROM stdin;
10	1	c5a13a44-d8ba-4ca9-9ce9-a81b4f4ab747	8429eecd-fd74-4d0d-903a-35b6b36d800b	b19f0cdc-0464-4119-a54c-8d201b3b7fef	áo thun của nike	áo thun nike	Active
10	2	c5a13a44-d8ba-4ca9-9ce9-a81b4f4ab747	2253ea87-5c41-46d0-a7ee-b643c5f2e8cd	a8ff87bf-fec7-4ca5-98ac-b4df98890c24	áo thun của nike	áo thun nike	Active
10	3	c5a13a44-d8ba-4ca9-9ce9-a81b4f4ab747	74d8c059-5f7f-4725-b797-bf4b4d19804b	35438af8-f567-4daf-8914-ddd32a993817	áo thun của nike	áo thun nike	Active
\.


--
-- Data for Name: purchase_order_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchase_order_details (quantity, id, guid, product_guid, purchase_order_guid) FROM stdin;
2	1	c21de9a6-28cd-44bf-a35e-3f49243d8c6a	8429eecd-fd74-4d0d-903a-35b6b36d800b	3d8742e9-79d6-4dc1-90c1-57f32afcca08
\.


--
-- Data for Name: purchase_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchase_orders (total_price, id, guid, supplier_guid, description, is_active) FROM stdin;
100000	1	3d8742e9-79d6-4dc1-90c1-57f32afcca08	f106f51a-b04b-43d0-ac85-d29fc17b5d1d	mua ao nike	in process
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, guid, description, role_name) FROM stdin;
1	325c8559-4e35-463c-860d-53d44b355fcf	Staff of system	Staff
2	1ef6bef7-253e-4da1-af03-6d0a4c0b0437	admin	admin
3	d8b1b7bc-c44c-411b-bd7f-dfd485d0a150	manager of system	manager
\.


--
-- Data for Name: suggest_purchase_order_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suggest_purchase_order_products (price, quantity, id, suggest_purchase_order_id, product_guid) FROM stdin;
50000	2	1	1	8429eecd-fd74-4d0d-903a-35b6b36d800b
\.


--
-- Data for Name: suggest_purchase_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suggest_purchase_orders (price, quantity, create_date, id, guid, supplier_guid, user_guid, description, is_active) FROM stdin;
100000	1	2025-05-12 23:20:57.722482	1	3464f65b-f1ba-4561-ac24-737ba817eccb	f106f51a-b04b-43d0-ac85-d29fc17b5d1d	5720aeb7-7024-405d-b620-49e7b7da7b05	string	active
\.


--
-- Data for Name: supplier_performance; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.supplier_performance (on_time_delivery_rate, product_quality_rating, supply_completion_rate, id, consignment_guid, guid, supplier_guid, user_guid, description) FROM stdin;
\.


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suppliers (id, guid, address, email, is_active, name, phone) FROM stdin;
1	f106f51a-b04b-43d0-ac85-d29fc17b5d1d	nike street	nike@gmail.com	Active	nike	123123123
2	cb40a36c-e6d3-4764-b684-d868eb1b733f	adidas street	adidas@gmail.com	Active	adidas	123123123
\.


--
-- Data for Name: system_configs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.system_configs (id, config_value, description, name) FROM stdin;
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (money, create_date, id, customer_guid, guid, description) FROM stdin;
\.


--
-- Data for Name: transfer_requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transfer_requests (quantity, create_date, from_inventory_guid, guid, product_guid, to_inventory_guid, user_guid, note) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (is_active, id, guid, role_guid, contact_info, email, password, username) FROM stdin;
t	1	a3b8441c-3e29-4e86-843c-c36f97653385	1ef6bef7-253e-4da1-af03-6d0a4c0b0437	0123456789	anhtuan@gmail.com	123456	anhtuan
t	2	5720aeb7-7024-405d-b620-49e7b7da7b05	325c8559-4e35-463c-860d-53d44b355fcf	0123456789	ductoan@gmail.com	123456	ductoan
t	3	a6cee098-ea38-4693-9d28-5a1b56b5589a	d8b1b7bc-c44c-411b-bd7f-dfd485d0a150	0123456789	thanhkim@gmail.com	123456	thanhkim
\.


--
-- Data for Name: variants; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.variants (id, guid, color, size) FROM stdin;
1	ef2a478e-6bb0-4223-a551-f84585ee4be5	white	S
2	35438af8-f567-4daf-8914-ddd32a993817	black	S
3	b19f0cdc-0464-4119-a54c-8d201b3b7fef	red	S
4	f79c7253-f355-478e-ba38-269990693f13	blue	S
5	2c2f50d4-89a4-47b5-8bd5-6357964d1cbf	blue	M
6	681a1cd5-785b-499b-8828-7f5882576da8	blue	L
7	e17124b5-a434-453d-8b12-2dd16c22fc39	white	M
8	a8ff87bf-fec7-4ca5-98ac-b4df98890c24	white	L
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 4, true);


--
-- Name: consignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.consignments_id_seq', 1, true);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 2, true);


--
-- Name: inventories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventories_id_seq', 1, false);


--
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.locations_id_seq', 1, false);


--
-- Name: order_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_details_id_seq', 1, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 2, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 3, true);


--
-- Name: purchase_order_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchase_order_details_id_seq', 1, true);


--
-- Name: purchase_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchase_orders_id_seq', 1, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 3, true);


--
-- Name: suggest_purchase_order_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suggest_purchase_order_products_id_seq', 1, true);


--
-- Name: suggest_purchase_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suggest_purchase_orders_id_seq', 1, true);


--
-- Name: supplier_performance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supplier_performance_id_seq', 1, false);


--
-- Name: suppliers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suppliers_id_seq', 2, true);


--
-- Name: system_configs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.system_configs_id_seq', 1, false);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: variants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.variants_id_seq', 8, true);


--
-- Name: categories categories_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_guid_key UNIQUE (guid);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: consignments consignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consignments
    ADD CONSTRAINT consignments_pkey PRIMARY KEY (id);


--
-- Name: consignments consignments_sku_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consignments
    ADD CONSTRAINT consignments_sku_key UNIQUE (sku);


--
-- Name: customers customers_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_guid_key UNIQUE (guid);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: inventories inventories_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_guid_key UNIQUE (guid);


--
-- Name: inventories inventories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventories
    ADD CONSTRAINT inventories_pkey PRIMARY KEY (id);


--
-- Name: locations locations_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_guid_key UNIQUE (guid);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: order_details order_details_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_guid_key UNIQUE (guid);


--
-- Name: order_details order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);


--
-- Name: orders orders_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_guid_key UNIQUE (guid);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_guid_key UNIQUE (guid);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: purchase_order_details purchase_order_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_details
    ADD CONSTRAINT purchase_order_details_pkey PRIMARY KEY (id);


--
-- Name: purchase_orders purchase_orders_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_guid_key UNIQUE (guid);


--
-- Name: purchase_orders purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);


--
-- Name: roles roles_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_guid_key UNIQUE (guid);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: suggest_purchase_order_products suggest_purchase_order_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_order_products
    ADD CONSTRAINT suggest_purchase_order_products_pkey PRIMARY KEY (id);


--
-- Name: suggest_purchase_orders suggest_purchase_orders_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_orders
    ADD CONSTRAINT suggest_purchase_orders_guid_key UNIQUE (guid);


--
-- Name: suggest_purchase_orders suggest_purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_orders
    ADD CONSTRAINT suggest_purchase_orders_pkey PRIMARY KEY (id);


--
-- Name: supplier_performance supplier_performance_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier_performance
    ADD CONSTRAINT supplier_performance_guid_key UNIQUE (guid);


--
-- Name: supplier_performance supplier_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier_performance
    ADD CONSTRAINT supplier_performance_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_guid_key UNIQUE (guid);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: system_configs system_configs_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_configs
    ADD CONSTRAINT system_configs_name_key UNIQUE (name);


--
-- Name: system_configs system_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_configs
    ADD CONSTRAINT system_configs_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_guid_key UNIQUE (guid);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: transfer_requests transfer_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transfer_requests
    ADD CONSTRAINT transfer_requests_pkey PRIMARY KEY (guid);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_guid_key UNIQUE (guid);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: variants variants_guid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.variants
    ADD CONSTRAINT variants_guid_key UNIQUE (guid);


--
-- Name: variants variants_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.variants
    ADD CONSTRAINT variants_pkey PRIMARY KEY (id);


--
-- Name: purchase_orders FK27odvxtv2d2w20lsg9qh3ycte; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT "FK27odvxtv2d2w20lsg9qh3ycte" FOREIGN KEY (supplier_guid) REFERENCES public.suppliers(guid);


--
-- Name: products FK3mn9fcv8gawky7rgwnes0e5uf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FK3mn9fcv8gawky7rgwnes0e5uf" FOREIGN KEY (category_guid) REFERENCES public.categories(guid);


--
-- Name: suggest_purchase_order_products FK6a2i0qfvmk80ajh2suo7v49hl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suggest_purchase_order_products
    ADD CONSTRAINT "FK6a2i0qfvmk80ajh2suo7v49hl" FOREIGN KEY (suggest_purchase_order_id) REFERENCES public.suggest_purchase_orders(id);


--
-- Name: products FKauhtqrx1mr4b5w6aw3vx7cwk0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FKauhtqrx1mr4b5w6aw3vx7cwk0" FOREIGN KEY (variant_guid) REFERENCES public.variants(guid);


--
-- Name: orders FKdy1mqg6b9c230kh8ndnbh4775; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "FKdy1mqg6b9c230kh8ndnbh4775" FOREIGN KEY (customer_guid) REFERENCES public.customers(guid);


--
-- Name: transactions FKhva4f7ywanet2v96e4uft4xyp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT "FKhva4f7ywanet2v96e4uft4xyp" FOREIGN KEY (customer_guid) REFERENCES public.customers(guid);


--
-- Name: purchase_order_details FKjer4t22d66ip6hj11xkery5wd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_details
    ADD CONSTRAINT "FKjer4t22d66ip6hj11xkery5wd" FOREIGN KEY (purchase_order_guid) REFERENCES public.purchase_orders(guid);


--
-- Name: order_details FKk3r4d3kuu7vo4nassvxjteqpb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "FKk3r4d3kuu7vo4nassvxjteqpb" FOREIGN KEY (product_guid) REFERENCES public.products(guid);


--
-- Name: order_details FKoqqgvqga60e9clqfa3yjbwd8k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "FKoqqgvqga60e9clqfa3yjbwd8k" FOREIGN KEY (order_guid) REFERENCES public.orders(guid);


--
-- PostgreSQL database dump complete
--

